apiVersion: v1
kind: ReplicationController
metadata:
  name: demo70
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo70
  template:
    metadata:
      labels:
        app: demo70
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo70
        image: ${docker-registry}/${docker-namespace}/demo70:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080